### ISSUE TITLE
cannot build unsigned release APK

### ISSUE THREAD

**Issue by IzzySoft** [dessalines/rank-my-favs#174]
### Steps to reproduce

Since you switched to `build.gradle.kts`, I can no longer build an unsigned release APK as you enforce signing. That means, no more reproducible builds at IzzyOnDroid. Could you please tell me how to create an `*unsigned.apk`?

### Expected behavior

`./gradlew assembleRelease` produces unsigned APK if no keystore exists

### Actual behavior

it creates an `app-release.apk` (with debug signing?)

### version of the program

0.5.3

### Android version

n/a

### Device

n/a

### Other details

same most likely applies to thumbkey, which had it's RB failing today as well.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by IzzySoft** [comment]
OK, found the trick:

    sed -r 's/signingConfigs.getByName\("(release|debug)"\)/signingConfigs.findByName("none")/' -i app/build.gradle.kts

It's RB again. Apologies for the noise. Will try the same trick on thumbkey now as well…

**Comment by dessalines** [comment]
No probs. I'm confused as to why that's necessary for these two, but not jerboa, because jerboa has the exact same signing configuration: https://github.com/LemmyNet/jerboa/blob/main/app/build.gradle.kts#L70

But I see that my blocks are different from what they [currently recommend](https://developer.android.com/studio/publish/app-signing#secure-shared-keystore), so I'll try those out.

**Comment by dessalines** [comment]
I think I found the issue. I'll fix it in a PR rn.

**Comment by IzzySoft** [comment]
OK, worked for thumbkey as well.

Note to self: if the resulting APK is signed by a debug key, it doesn't help to disable just the release signing :see_no_evil:

```kotlin
signingConfig = if (project.hasProperty("RELEASE_STORE_FILE")) {
```

No such file, so it must be the **else** part :bulb:

> I'm confused as to why that's necessary for these two, but not jerboa

I cannot tell, Jerboa is not in my builder. Hm, wild guess: maybe you're speaking of F-Droid's building? Different tooling. They trust a lot in "magic", removing all signing related stuff automatically. At IzzyOnroid, we don't – so when setting up recipes, we deal with all changes applied to the app's code **explicitly**. For example, here's the complete block for 0.5.3 of rank-my-favs:

```yaml
  - tag: 0.5.3
    apks:
      - apk_pattern: app-release\.apk
        apk_url: https://github.com/dessalines/rank-my-favs/releases/download/0.5.3/app-release.apk
        build:
          - sed -r 's/signingConfigs.getByName\("(release|debug)"\)/signingConfigs.findByName("none")/' -i app/build.gradle.kts
          - chmod +x gradlew
          - ./gradlew assembleRelease
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```
